// The 195 countries that count towards the tally: the 193 UN member states
// plus Vatican City and Palestine. Names are the exact properties.name
// strings from world-atlas countries-50m, so they key straight into the map.
//
// Territories and disputed areas — Greenland, Puerto Rico, Taiwan, Kosovo,
// Western Sahara and the rest — are deliberately absent. They stay on the map
// and can be scratched, they just do not count towards the total.

const SOVEREIGN_COUNTRIES = [
  "Afghanistan", "Albania", "Algeria",
  "Andorra", "Angola", "Antigua and Barb.",
  "Argentina", "Armenia", "Australia",
  "Austria", "Azerbaijan", "Bahamas",
  "Bahrain", "Bangladesh", "Barbados",
  "Belarus", "Belgium", "Belize",
  "Benin", "Bhutan", "Bolivia",
  "Bosnia and Herz.", "Botswana", "Brazil",
  "Brunei", "Bulgaria", "Burkina Faso",
  "Burundi", "Cabo Verde", "Cambodia",
  "Cameroon", "Canada", "Central African Rep.",
  "Chad", "Chile", "China",
  "Colombia", "Comoros", "Congo",
  "Costa Rica", "Côte d'Ivoire", "Croatia",
  "Cuba", "Cyprus", "Czechia",
  "Dem. Rep. Congo", "Denmark", "Djibouti",
  "Dominica", "Dominican Rep.", "Ecuador",
  "Egypt", "El Salvador", "Eq. Guinea",
  "Eritrea", "Estonia", "eSwatini",
  "Ethiopia", "Fiji", "Finland",
  "France", "Gabon", "Gambia",
  "Georgia", "Germany", "Ghana",
  "Greece", "Grenada", "Guatemala",
  "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Honduras", "Hungary",
  "Iceland", "India", "Indonesia",
  "Iran", "Iraq", "Ireland",
  "Israel", "Italy", "Jamaica",
  "Japan", "Jordan", "Kazakhstan",
  "Kenya", "Kiribati", "Kuwait",
  "Kyrgyzstan", "Laos", "Latvia",
  "Lebanon", "Lesotho", "Liberia",
  "Libya", "Liechtenstein", "Lithuania",
  "Luxembourg", "Macedonia", "Madagascar",
  "Malawi", "Malaysia", "Maldives",
  "Mali", "Malta", "Marshall Is.",
  "Mauritania", "Mauritius", "Mexico",
  "Micronesia", "Moldova", "Monaco",
  "Mongolia", "Montenegro", "Morocco",
  "Mozambique", "Myanmar", "Namibia",
  "Nauru", "Nepal", "Netherlands",
  "New Zealand", "Nicaragua", "Niger",
  "Nigeria", "North Korea", "Norway",
  "Oman", "Pakistan", "Palau",
  "Palestine", "Panama", "Papua New Guinea",
  "Paraguay", "Peru", "Philippines",
  "Poland", "Portugal", "Qatar",
  "Romania", "Russia", "Rwanda",
  "S. Sudan", "Saint Lucia", "Samoa",
  "San Marino", "São Tomé and Principe", "Saudi Arabia",
  "Senegal", "Serbia", "Seychelles",
  "Sierra Leone", "Singapore", "Slovakia",
  "Slovenia", "Solomon Is.", "Somalia",
  "South Africa", "South Korea", "Spain",
  "Sri Lanka", "St. Kitts and Nevis", "St. Vin. and Gren.",
  "Sudan", "Suriname", "Sweden",
  "Switzerland", "Syria", "Tajikistan",
  "Tanzania", "Thailand", "Timor-Leste",
  "Togo", "Tonga", "Trinidad and Tobago",
  "Tunisia", "Turkey", "Turkmenistan",
  "Tuvalu", "Uganda", "Ukraine",
  "United Arab Emirates", "United Kingdom", "United States of America",
  "Uruguay", "Uzbekistan", "Vanuatu",
  "Vatican", "Venezuela", "Vietnam",
  "Yemen", "Zambia", "Zimbabwe",
];
